### PR TITLE
Add log-level to context attributes from Context Attribute Backlog

### LINKED ISSUE #27: log-level context attribute
This is a proposed metadata attribute (from Context Attribute Backlog):

log-level
    Type: String
    Description: The level of logging that the publisher may want to log this specific event (e.g. debug)

### PR DESCRIPTION
**Pull request by vbmade2000**
Fixes #27

Signed-off-by: Malhar Vora <mlvora.2010@email.com>

### CODE REVIEW

**Comment by duglin** [comment]
rebase needed

**Comment by schatekar** [comment]
Is this a duplicate of #63 ?

**Comment by duglin** [comment]
@schatekar good catch. @vbmade2000 I'm going to close this one because it looks like #63 has the same change w/o the other commits included that should not be there. If I got it wrong please let me know.

**Comment by vbmade2000** [comment]
@duglin Sure.

**Pull request closed without merging**
