### PR TITLE
CESQL AND operators are now short-circuit evaluated

### PR DESCRIPTION
**Pull request by Cali0707**
Follow up on #1267 

## Proposed Changes

- CESQL AND operations are short-circuit evaluated

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Review by jskeet — APPROVED** [review]

**Comment by duglin** [comment]
@Cali0707 were you going to tweak this?

**Comment by Cali0707** [comment]
@duglin yes, sorry for the delay - a few things came up at work today and I ran out of time . I’ll try and update this on Monday

**Comment by duglin** [comment]
Approved on the 3/21 call - just waiting for a minor wording tweak before merging.

**Comment by Cali0707** [comment]
@duglin @jskeet I added the wording changes as best as I could remember them from the call last week

**Review by jskeet — APPROVED** [review]
Yup, that works for me.

**Comment by duglin** [comment]
Cool - thanks! Merging.

**Pull request merged**
