### PR TITLE
add a use case for correlation of multiple events

### PR DESCRIPTION
**Pull request by cathyhongzhang**
Signed-off-by: cathyhongzhang <cathy.h.zhang@huawei.com>

### CODE REVIEW

**Comment by duglin** [comment]
@cathyhongzhang can you rebase?

**Comment by cathyhongzhang** [comment]
How about I do a new PR which might be simpler than rebase?

**Comment by duglin** [comment]
I guess if you really wanted to, but it might be a good learning experience  :-)

If you don't want that much excitement, I can try to do the rebase for you if you want.

**Comment by inlined** [comment]
1. Was it intentional to delete data in `spec.md`? I'm not entirely against this since this aligns closely with my vision that context and data are clearly separate, though that might be a different PR.
2. How would an implementer of your burglary detection system know to correlate a particular window open and motion detection event? Is this likely just that the first event after a period of inactivity starts a new house-wide correlation ID? I'm trying to think about whether this is best implemented in the IoT gateway or the delivery infrastructure.

**Comment by duglin** [comment]
LOL that's funny - I didn't notice the deletion of `data`.  @cathyhongzhang can you fix that?

**Comment by cathyhongzhang** [comment]
@inlined @duglin  I have fixed it and will do the removal of the data from Context Attributes in a separate PR. 

Good question. W.r.t. the burglary detection system, the correlation-token/id could be the house address or any other unique identifier of that house . In order to support a burglary detection system on serverless framework, this correlation-token value must be carried in both the window/door open event and the motion event. Based on the correlation-token, the serverless platform/infrastructure can then correlate the window/door open event instance with the motion event instance that are associated with the same house and send them to the same burglary detection instance for processing. IoT GW could be a good place to add this correlation-token value. For use cases that involve other multiple events, the correlation-token value would be different.  In order to support consistency among event producers, we need to provide a standard way for them to specify the correlation token/id. Hope I answer your question:-)  You may want to take a look at PR #128 .

**Comment by duglin** [comment]
@cathyhongzhang thanks!

**Comment by cathyhongzhang** [comment]
@duglin Np. Yes, let's do it next week. It should be an easy one.

**Comment by deissnerk** [comment]
LGTM

**Comment by duglin** [comment]
Approved on 4/5 call

**Pull request merged**
