### PR TITLE
Vote: moving CESQL spec to v1

### PR DESCRIPTION
**Pull request by Cali0707**
We'll be using this PR to vote on moving the CESQL to v1.0.

The following community members have voting rights:  Google, IBM/Red Hat, Microsoft, SAP, Mark Peek, Erik Erikson, Tommy Chung.

Other folks are welcome, and encouraged, to vote as well, but only "voting rights" members votes will be counted.

Please vote either with a thumb-up or thumb-down emoji on this comment, or with a new github comment.

The vote will close at the start of the next weekly call - June 13, 12pm ET.

Note: technically, IBM/Red Hat forgot to change their representatives in our tracking spreadsheet so they're not officially listed as having voting rights. However, @Cali0707 has been at the last 4 meetings so Red Hat really should have voting rights. I'll work with Calum on getting the spreadsheet updated.

Additionally, Mark Peek was listed as the rep for VMWare but he moved on earlier this year and the spreadsheet was not updated, so I've adjusted the comments in this PR to reflect this.

## Proposed Changes

- Mark spec as v1.0

**Release Note**

```release-note
The CloudEvents SQL Specification is now version 1.0
```

### CODE REVIEW

**Comment by duglin** [comment]
ping @jskeet @deissnerk @markpeek, @erikerikson

**Comment by jskeet** [comment]
I'm afraid I'm absolutely slammed with other things at the moment, and won't be able to look again. I believe all the issues I raised before have been addressed though.

**Comment by duglin** [comment]
Note, there may need to another PR after this one to fix-up some of the main READE links, but we'll do those after we create the new release branch. In case anyone was wondering....

@jskeet is that an implied +1 or "abstain" ?

**Comment by jskeet** [comment]
Happy for it to be a +1

**Comment by erikerikson** [comment]
Congratulations on this milestone!  While I formally abstain, I support this overdue release.

**Comment by deissnerk** [comment]
SAP votes +1

**Comment by markpeek** [comment]
+1

**Comment by Cali0707** [comment]
Red Hat votes +1

**Comment by duglin** [comment]
Vote tally:
- Google: yes - Jon
- IBM/Red Hat: yes - Calum
- Microsoft: yes - Doug
- SAP: yes - Klaus
- VMware: yes - Mark
- Erik Erikson: abstain
- Tommy Chung: ?

**Comment by duglin** [comment]
Approved PR changes and move to v1.0 on the 6/13 call. See comment above for voting summary.

**Pull request merged**
