### PR TITLE
docs: add common processes for SDK maintainers and contributors

### PR DESCRIPTION
**Pull request by lance**
This commit adds recommended guidelines for SDK maintainers and external contributors. 

TODO: Should we consider changing the default branch from `master` to `main` on this and SDK repositories?

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by lance** [comment]
Regarding the default branch name: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by slinkydeveloper** [comment]
Does it makes sense to have these documents under the `governance` directory like in #649?

**Comment by duglin** [comment]
> Does it makes sense to have these documents under the `governance` directory like in #649?

Yes I've been wondering the same thing. I'll add this to my proposed repo restructuring

**Comment by lance** [comment]
Happy to move them to `/governance` if that's what's requested. Just let me know.

**Comment by duglin** [comment]
I like `/governance` just to keep the top level stuff to a minimum. I think it's ok for sdk and ce governance to live in one dir for now.

**Comment by duglin** [comment]
Approved on the 7/2 call

**Pull request merged**
