### PR TITLE
Add "Version 0.1" to some md files in prep for release

### PR DESCRIPTION
**Pull request by duglin**
Also added a "Status" section to be consistent across all 3 docs.

This should address @inline's concern about people thinking anything
is set in stone because now it says its a 'working draft'.

One thing we need to decide, later, is whether to have section numbers or not, we not consistent right now.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by markpeek** [comment]
LGTM

**Comment by clemensv** [comment]
LGTM as-is. 

I would appreciate if we'd formalize spec editor status as in most other bodies of this sort and then reflect that in the docs.

**Comment by duglin** [comment]
Syntax/editorial changes in prep for v0.1 - got 2 LGTMs, merging.

**Comment by yaronha** [comment]
LGTM

**Pull request merged**
