### PR TITLE
Clarify contentType

### PR DESCRIPTION
**Pull request by clemensv**
There has been a good deal of confusion about the role of contentType and whether it designates the contentType of the event per-se or of the event's data attribute. This change clarifies that it is meant to designate the content type of the latter. The content type of the event encoding is defined by the respective event format.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
Last discussed on the 4/26 call: https://www.youtube.com/watch?v=PsMF2ddWNbw&t=0s&index=4&list=PLj6h78yzYM2Ph7YoBIgsZNW_RGJvNlFOt

**Comment by duglin** [comment]
Discussed around 43 minutes into the video.

@clemensv  agreed to add some text around the relationship between the transport used and the encoding of `data`

**Comment by scothis** [comment]
@clemensv Can you also clarify the relationship between `contentType` and `eventType`/ `eventTypeVersion`? In HTTP/ReST the responsibility of all three attributes is consolidated within the `Content-Type` header.

There is a distinction between the semantic meaning and the encoding of `Content-Type`. It seems CloudEvents is demoting `contentType` to only be concerned with the encoding of `data` while `eventType` and  `eventTypeVersion` are concerned with the semantic meaning. How should an implementer handle a case where the `contentType` of the event also conveys semantic meaning?

Additionally, `schemaURL` appears to be attempting to convey semantic meaning as well creating a third place where the semantic meaning can exist, and potentially be in conflict. As an implementor, what defines the semantic meaning of the event? Especially if these attributes are in conflict or ambiguous.

**Comment by clemensv** [comment]
@scothis eventType relates to the entire event, the contentType here only to the payload, so these are different scopes.

**Comment by johnmccabe** [comment]
Should the default `contentType` be explicitly defined for cases when its omitted? `application/json` when `data` contains an object, `text/plain` when its a string? Would need added to the `Special Handling of the "data" Attribute` section.

**Comment by clemensv** [comment]
@johnmccabe Let me add a clause for what omitting the field means.

**Comment by duglin** [comment]
All - this PR was updated last week so please review it when you get a chance so we can vote on it at the f2f.

**Comment by duglin** [comment]
Approved during 6/15 f2f

**Pull request merged**
