### PR TITLE
Add extension for Distributed Tracing spec.

### PR DESCRIPTION
**Pull request by inlined**
I think this merits the initial statnce of being an extension
for a few reasons:

1. I want to adhere to the CNCF policy against kingmaking even
   though I think the world is better off with one interoperable
   tracing standard.
2. Nothing in the trace state should have an effect on
   application logic.
3. I like exercising our thoughts on extensions.

### CODE REVIEW

**Comment by duglin** [comment]
Just a few minor thing, but otherwise LGTM.

Reviewers... since the "extensions.md" doc isn't going to be an official deliverable from our WG, the bar is pretty low on this. We don't all need to agree on whether we like the extension or not, rather just that its in scope for the WG (ie. related to cloud events), its written well to be understand by other people and can be implemented.  These are just "experimental" properties with no official standing. 

@inlined thanks for being the first!

**Comment by jroper** [comment]
I'm not that familiar with the distributed tracing spec, so correct me if I'm wrong. I think this is very closely related to #24 and #25. I think if we accept this, then #24 and #25 would just be duplication of fields for achieving the same purpose. Also somewhat vice versa. I don't think CloudEvents should support (whether it's an extension or part of the top level spec) two different mechanisms for attaching trace metadata, that would just be confusing and defeat the purpose because if one party used one, and another used another, then the tracing would not work.

So I think a decision should be made as to whether CloudEvents should be opinionated on supporting and requiring distributing tracing as the tracing mechanism, or whether it should do something differently.

On whether this is an extension or part of the top level spec - I'm not sure that I see the difference between one or the other. The most important thing is that different vendors using this all use the same field names and value format. Whether it's an extension, or part of the spec proper, doesn't seem to make any difference, the consequences of adding it, of maintaining it, of ensuring that it's consistent between each use, are the same either way. I guess what I'm saying is I don't see the point of CloudEvents having any extensions that it documents itself, since I don't see the expectations being any different either way. Extensions should be something that specific transports use that CloudEvents knows nothing about, if it's something that's not transport specific that CloudEvents does document somewhere, then it may as well go in the spec.

**Comment by inlined** [comment]
This is an interesting idea that correlation-id and causation-id would be replaced by this. For correlation, I personally believe that allowing a single ID is a non-goal because we edge into encoding event usage into the event envelope (correlation-id is easily a topic ID which was already decided to be a non-goal). Distributed Tracing also has a "Correlation-Context" which I'm much more open to because it has a property bag and tools can choose which field to route on.

Causation ID is much more interesting. I somehow assumed this was meant for the time series use case. If it's just meant to help correlate the thing that caused an event to the event itself, then I definitely agree in a standards-based approach instead.

**Comment by duglin** [comment]
Approved during 6/15 f2f. We also agreed to:
- Thomas: put each extension in its own doc in an “extensions” dir. Talk about how the RFC2119 keywords only apply IFF the extension is being used
- Clemens: Need an “escape hatch” in our binding specs to allow attributes to override the serialization rules defined.

**Pull request merged**
