### PR TITLE
Update the href checker tool

### PR DESCRIPTION
**Pull request by duglin**
Mainly to pickup a fix for when an image as a "title" associated with it.

This was noticed due to Sarah's PR that included an image with a "title" associated with it.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by ultrasaurus** [comment]
ran this locally and got an error:

```
./tools/verify-links.sh -v
> ./tools/../CONTRIBUTING.md
> ./tools/../GOVERNANCE.md
> ./tools/../README.md
> ./tools/../spec.md
./tools/../spec.md: Can't find referenced file './tools/../} ```
```

**Comment by ultrasaurus** [comment]
I looked at this a bit, and it seems that Macs interpret newlines in a special way, so this may work for other and on travis.

**Comment by duglin** [comment]
fixed because mac's bash is  "special"  :-)

**Comment by duglin** [comment]
Approved on 2/8 call

**Pull request merged**
