### PR TITLE
fix how we remove punct from links

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@microsoft.com>

### CODE REVIEW

**Comment by duglin** [comment]
ping @JieDing to check the Chinese file edits

**Comment by duglin** [comment]
@JieDing the TOC seems to be fixed now for the spec.md

**Comment by duglin** [comment]
@JieDing do these edits to the docs look ok to you?

**Comment by JieDing** [comment]
> @JieDing do these edits to the docs look ok to you?

Yes, I checked these edits.  LGTM, but are TOC problems fixed already by these edits?

**Comment by duglin** [comment]
@JieDing yes from my testing the TOC problem appears to be fixed.

**Comment by duglin** [comment]
to unblock people i'm going to merge this since it's mainly a tooling/href fix - no real text/spec changes.

**Pull request merged**
