### PR TITLE
add logo artwork

### PR DESCRIPTION
**Pull request by ac360**
Adds updated artwork to the repository.

### CODE REVIEW

**Comment by duglin** [comment]
woo hoo!  Thanks

**Comment by duglin** [comment]
LGTM
I'm assuming once approved by the WG we'll need to update our website with the new images.
@barkerd427 is this something you'll have time to do?

**Comment by n3wscott** [comment]
is it too similar to CE Mark ?

**Comment by barkerd427** [comment]
@duglin, yep. I can take care of it once it's approved. LGTM

**Comment by duglin** [comment]
Approved on the 8/30 call

**Pull request merged**
