### PR TITLE
I think there was a typo in the table here

### PR DESCRIPTION
**Pull request by danhawkins**

### CODE REVIEW

**Comment by duglin** [comment]
good catch

@danhawkins can you sign your commit so the DCO checker is happy?

**Comment by duglin** [comment]
Approved on the 7/23 call - just waiting for DCO

**Comment by danhawkins** [comment]
Added the DCO sign, sorry for the delay, I thought I did it the first time 🤦

**Comment by duglin** [comment]
No worries - thanks for the PR.
Merging....

**Pull request merged**
