### PR TITLE
Rename attributes 'resource*' to 'source*' 

### LINKED ISSUE #38: Rename attributes 'resource*' to 'source*' or 'producer*'
Rename attributes 'resource*' to 'source*', or alternatively 'producer*', for clarity.

Assigned to: @lfourie

### PR DESCRIPTION
**Pull request by lfourie**
Closes #38

### CODE REVIEW

**Comment by sslavic** [comment]
Have few somewhat related questions:
1. Does `namespace` identify event or event source (producer)?
2. If latter, what is the value `namespace` adds on top of `source-id`?
3. Is there a use case where events with same (event-type, event-type-version) can be published by more than one event source, so with difference in one of (source-id, source-type)?
4. If `namespace` identifies event source and there's value added of `namespace` on top of `source-id` would it make sense to include `namespace` together with (`source-id`, `source-type`) as property of `source` object?

**Comment by duglin** [comment]
@lfourie you'll need to sign your commit

**Comment by sslavic** [comment]
Created https://github.com/cloudevents/spec/issues/41

**Comment by duglin** [comment]
@sslavic thanks!

**Comment by duglin** [comment]
@lfourie can you please sign your commit - I think we might be able to resolve this one quickly on the next call but we can't merge it unless its signed.

**Comment by duglin** [comment]
LGTM once signed

**Comment by sslavic** [comment]
@lfourie why close this one? It hasn't been merged. As @duglin suggested, before it can be merged, commit needs to be amended with sign-off info, as per contributing guidelines https://github.com/cloudevents/spec/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by sslavic** [comment]
@lfourie just saw the PR and that you added a comment there with sign-off info. If I'm not mistaken, sign-off info has to be in the git commit message itself, so once commit is merged sign-off remains in the repo.

**Comment by duglin** [comment]
@lfourie I reopened this one and fixed your DCO

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by ultrasaurus** [comment]
I like the change from resource => source.  I think it is a lot clearer than original naming!

**Comment by deissnerk** [comment]
LGTM

**Comment by dklyle** [comment]
LGTM

**Comment by duglin** [comment]
Approved on Feb 1st call.
AI: Thomas to open issue to reconsider the name
AI: Thomas to work on new wording for definition of “source”

**Pull request merged**
