### PR TITLE
 Make it clear that schema-url is about 'data' and not the entire event 

### LINKED ISSUE #34: Does event-type-version apply to the entire event or only the data payload?
Decide and document if the [`event-type-version`](https://github.com/cloudevents/spec/blob/master/spec.md#event-type-version) attribute is applicable to the whole event or to the data payload alone. Currently, `event-type-version` covers the data, while `open-events-version` covers the context.

Assigned to: @duglin

### LINKED ISSUE #35: Does schema-url apply to the whole event or to the data alone?
Decide and document if the [schema-url](https://github.com/cloudevents/spec/blob/master/spec.md#schema-url) attribute is applicable to the whole event or to the data alone.

Assigned to: @duglin

### PR DESCRIPTION
**Pull request by duglin**
Closes #35
Closes #34

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
Note, this is based off of #15, so look at the 2nd commit to see the one-line change this PR is proposing.

**Comment by sslavic** [comment]
LGTM

**Comment by duglin** [comment]
Travis failures are due to needing #15 merged first

**Comment by schatekar** [comment]
LGTM

**Comment by ac360** [comment]
LGTM.  Great clarity.

**Comment by duglin** [comment]
Approved on 2/8 call

**Pull request merged**
