### PR TITLE
Update spec with OpenStack Event

### PR DESCRIPTION
**Pull request by notque**
Add OpenStack event example to references.

Signed-off-by: Nathan Oyler <nathan.oyler@sap.com>

### CODE REVIEW

**Comment by duglin** [comment]
@notque see: https://github.com/cloudevents/spec/issues/19
I think that entire section will be moved into a different doc. Perhaps you could use this PR to start that process? Meaning, 1) start a new doc, 2) move that References section into the new doc, 3) add the OpenStack event stuff into it.  WDYT?

**Comment by duglin** [comment]
yes! excellent! thanks!

If its ok with you, I'll assign you the owner of #19 since you already did the work ;-)
I think you just now need to sign your commits so that the DCO checker is happy.

**Comment by notque** [comment]
I've signed my commits, did I miss one? What is the most reasonable way to clear it?

**Comment by duglin** [comment]
I think if you squash it down to one and make sure that one is signed then it might help.
Also make sure you sign it via the "-s" flag on "git commit". It expects it in a certain format (something like: Signed-off-by: xxx <xxx@xxx.com> )  and its kind of picky about each char.
Make sure your git config user.name matches what appears in the git log too.

**Comment by duglin** [comment]
rebase needed

**Comment by duglin** [comment]
@notque can you rebase this? I think we can get this one merged this week - seems pretty straightforward.

**Comment by ac360** [comment]
Good addition, @notque.  Thanks!

**Comment by duglin** [comment]
@notque if you need help with your DCO or squashing ping me via slack (or here)

**Comment by notque** [comment]
@duglin Looking into the details of our agreement with CNCF, I actually have to jump through more hoops than I anticipated (as our team contributes to open source regularly), given that I am waiting for the right approval. Once that happens I can squash.

**Comment by ultrasaurus** [comment]
oops -- missed this!  I just did a PR to move the references section out of the spec: https://github.com/cloudevents/spec/pull/89

**Comment by duglin** [comment]
@notque any update on your CLA?

**Comment by duglin** [comment]
Approved on 2/22 call

**Pull request merged**
