### PR TITLE
Schema Registry - Change version to comply with OpenAPI spec

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
Did a quick search and found this: https://swagger.io/docs/specification/basic-structure/ 
Notice no quotes when in yaml. Does it matter?

**Comment by tomkerkhove** [comment]
Odd, I was using their [editor](https://editor.swagger.io/) which threw the error:
image

Probably because of this:
>  `version` is an arbitrary string that specifies the version of your API (do not confuse it with file revision or the openapi version).

Which matches [this doc](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#infoObject) but I'm happy to abandon if you want.

**Comment by duglin** [comment]
Nope, i was just wondering. I think the quotes are nice :-)

LGTM

**Comment by duglin** [comment]
Approved on the 7/2 call

**Pull request merged**
