### PR TITLE
Update open-source.md

### PR DESCRIPTION
**Pull request by glennblock**
Adding Extend

### CODE REVIEW

**Comment by duglin** [comment]
@glennblock can you fix the DCO issue by signing your commit?

**Comment by duglin** [comment]
@glennblock if you fix the DCO issue I can merge this one easily

**Comment by glennblock** [comment]
I will fix it today.

**Comment by glennblock** [comment]
I'll just send another PR.

**Comment by glennblock** [comment]
OK done. I closed my PR and sent a new one with a single commit / sign off.

**Pull request closed without merging**
