### PR TITLE
Add highlighting to Primer JSON snippets

### PR DESCRIPTION
**Pull request by lucperkins**
This PR makes the CE primer a tiny bit prettier via syntax highlighting.

### CODE REVIEW

**Comment by duglin** [comment]
Aside from some indenting difference, what's changed? I'm not see it

**Comment by lucperkins** [comment]
@duglin The JSON snippets now have syntax highlighting, which IMO is an important readability improvement

**Comment by duglin** [comment]
It is browser specific thing? Or a plugin?  I don't see anything special:
image

**Comment by lucperkins** [comment]
@duglin Syntax highlighting is a well established convention that is observed throughout the other documents in the spec.

**Comment by duglin** [comment]
I'm not against adding the json tags, I'm just curious to see where it would show up since I've never seen it taken into account in a browser

**Comment by lucperkins** [comment]
Without highlighting:

Screen Shot 2019-11-20 at 10 05 54 AM

With highlighting:

Screen Shot 2019-11-20 at 10 06 33 AM

AFAIK it isn't browser specific. Again, I'm only enforcing standardization across the code samples in the spec.

**Comment by duglin** [comment]
LGTM
can I get one more LGTM?

**Pull request merged**
