### PR TITLE
Adding link to Pub/Sub binding

### PR DESCRIPTION
**Pull request by nachocano**
- Adding link to Google Cloud Pub/Sub binding in the proprietary specs file.

### CODE REVIEW

**Comment by nachocano** [comment]
To discuss in the next WG meeting. Thanks!

/assign @duglin @mikehelmick @n3wscott

**Comment by duglin** [comment]
LGTM thanks!
And I did a quick scan of the spec itself, and it looks good too.

**Comment by nachocano** [comment]
Awesome, thanks Doug for checking it out!

**Comment by nachocano** [comment]
@duglin can we get this one merged?

**Comment by duglin** [comment]
Yup sorry - didn't get a chance to process the results of the previous meeting yet.... merging now.

**Comment by duglin** [comment]
Approved on the 3/19 call

**Comment by nachocano** [comment]
Thanks Doug!

**Pull request merged**
