### PR TITLE
Specify encoding of kafka header keys and values and message key

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Closes https://github.com/cloudevents/spec/issues/570

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
I'm not a Kafka expert but it seems ok to me.
@clemensv @n3wscott any thoughts?
The addition of the `MUST`s might be a concern since that could technically mean it's a breaking change, however, if that was the intent all along then it might be ok.

**Comment by duglin** [comment]
@bluemonk3y any comments?

**Comment by duglin** [comment]
Anyone have any comments on this? We may approve it on the call tomorrow.... you've been warned  :-)

**Comment by bsideup** [comment]
@duglin so... did you? Can we have it merged now? :)

**Comment by duglin** [comment]
Yup - Approved on today's (3/12) call. Merging...

**Pull request merged**
