### PR TITLE
NATS transport binding

### PR DESCRIPTION
**Pull request by ColinSullivan1**
I'd like to propose a [NATS](https://nats.io) transport binding for CloudEvents, similar to the [HTTP](https://github.com/cloudevents/spec/pull/148) binding and proposed [MQTT](https://github.com/cloudevents/spec/pull/158) and [AMQP](https://github.com/cloudevents/spec/pull/157) bindings.  This PR borrows heavily from the MQTT proposal.

Signed-off-by: Colin Sullivan <colin@synadia.com>

### CODE REVIEW

**Comment by sslavic** [comment]
@ColinSullivan1 please rebase the PR/branch.
https://github.com/cloudevents/spec/pull/216 got merged and there's now trivial conflict to be resolved.

**Comment by ColinSullivan1** [comment]
@sslavic - Thanks, I'll add that.  Just confirming, do I set v0.1 as latest release?  I notice this PR has a v0.1 label.

**Comment by sslavic** [comment]
It has `v1.0` label, not `0.1`. Latter was released some time ago and documents available at that time were listed/tagged.

IMO for NATS transport binding document just master/draft reference would be enough for now. Later when next release is made, references for the documents in the release would be updated.

**Comment by duglin** [comment]
CI/href failure is real but expected/ok until PR is merged.

**Comment by alexellis** [comment]
Good to see this @ColinSullivan1, looks like the Makefile needs a rebase though.

**Comment by duglin** [comment]
I think the rebase is off a bit

**Comment by ColinSullivan1** [comment]
Yes, sorry, will fix.

**Comment by duglin** [comment]
Approved on 6/7 call

**Pull request merged**
