### PR TITLE
Add JSONSchema Validation

### LINKED ISSUE #272: Consider Providing JSON Schema Documents
http://json-schema.org/

Seems like there's a schema in JSON for describing JSON. I think it would make sense to have some json schema documents that match the described spec in the markdown.

### PR DESCRIPTION
**Pull request by dmlb2000**
This adds a JSONSchema validation document and some docs on how
to validate events in JSON.

Fix #272

Signed-off-by: David Brown <dmlb2000@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
Any reason you don't just amend the previous commits, in the old PRs, instead of creating entirely new PRs?  ;-)

**Comment by dmlb2000** [comment]
Git refuses to push the amended commit to the upstream branch.

**Comment by duglin** [comment]
hmm, did you add "-f" - I usually have to force it:
```
git add ...
git commit -s --amend --no-edit
git push origin xxx -f
```

**Comment by dmlb2000** [comment]
https://stackoverflow.com/questions/253055/how-do-i-push-amended-commit-to-the-remote-git-repository

Now granted this is older but, "Linus told me not to." was good enough for me ;)

**Comment by duglin** [comment]
Well, I know some folks don't like amend, but you still could push additional commits instead of doing a new PR each time.

**Comment by dmlb2000** [comment]
Well, I'm fine with amend. I just couldn't repoint the pull request to another branch name in my fork, which is a GitHub behavior. It could have been solved either way.

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
All, please review - this should be an easy one for us to approve quickly on the next call

**Comment by clemensv** [comment]
How does the schema look when there's no extensions bag but we allow arbitrary extra content as we're currently discussing, i.e. an open schema?

**Comment by dmlb2000** [comment]
https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.4 (especially check out the examples before sections 8.3)

I think the idea is that this json schema document would be used as the root official minimum definition for describing a CloudEvent. If other json schema documents would be needed to describe other types of events (like those with extensions) the definitions could be referenced from this document to create a new definition document.

The hope is that this json schema document along with additional documents could be hosted at some permanent URL so others could extend the base implementation.

Just a thought. Unless I'm not getting what you mean by "open schema?"

**Comment by erikerikson** [comment]
As mentioned on the call `additionalProperties` controls treatment of undeclared attributes observed in the described object.

> "By default any additional properties are allowed."
from: https://json-schema.org/understanding-json-schema/reference/object.html

**Comment by dmlb2000** [comment]
I'm not on any calls, so if you'd like me to fix things a certain way please be explicit.

Would you like me to add `"additionalProperties": false` to the event definition or not?

**Comment by duglin** [comment]
@dmlb2000 nope you're good - we approved the PR in the call and I'll be merging soon....

**Comment by duglin** [comment]
@erikerikson thanks for finding that info for us!!!

**Comment by erikerikson** [comment]
Apologies for the lack of context @dlmb2000 - a question was raised: what would happen during validation of a compliant object (against this schema) that also contained arbitrary extension attributes as they have been recently discussed?  The group didn't want to put itself in to contradiction with its current trajectory.

**Comment by dmlb2000** [comment]
Just my 2 cents on adding that option...

As your spec changes over time additional attributes might be added in the future to express new features. Would a v1.0 json schema document also be able to validate a v1.1 event with additional attributes as defined by the v1.1 spec?

The question is how do you want the spec to evolve over time, if you say additional attributes aren't allowed then you are stuck in a major version bump of the spec for potentially minor changes.

**Comment by duglin** [comment]
IMO a v1.0 schema needs to be able to validate a v1.1 event because anything new in v1.1 will appear as an optional extension and be ignore-able by a v1.0 receiver, if they wish.  The idea of not allowing a minor version bump to add new optional properties doesn't seem like a good choice to me  - or to turn it around, making the addition of a new optional property be a major version change seems extreme.

**Comment by duglin** [comment]
Approved on 8/16 call

**Comment by sslavic** [comment]
Btw, I just checked json example against schema, used https://www.jsonschemavalidator.net/ - validation fails at source field, since it’s not proper uri.

**Comment by dmlb2000** [comment]
@sslavic my thought is to put in another issue stating the example events in the spec are not valid.

There's two possible issues:

 1. The examples are correct and the code jsonschemavalidator.net is using is being too strict on what a valid URI is, they aren't following the [spec](https://tools.ietf.org/html/rfc3986#section-4.1).
 1. The examples aren't correct and need to be made valid.

**Pull request merged**
