### PR TITLE
Fix small typo in contribution file

### PR DESCRIPTION
**Pull request by vbmade2000**
Signed-off-by: Malhar Vora <mlvora.2010@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by vbmade2000** [comment]
@duglin Can you merge this ?

**Comment by duglin** [comment]
@vbmade2000 even though this is so trivial, since its not a blocker, I'd prefer to follow the agreed-to process and defer merging it until our weekly call. On the call I'll ask if people are ok with deviations to the process for trivial PRs like this though. ok?

**Comment by vbmade2000** [comment]
Sure. No worries.

**Comment by duglin** [comment]
Approved on 2/8 call

**Pull request merged**
