### PR TITLE
Clarification for the abuse protection callback

### PR DESCRIPTION
**Pull request by clemensv**
Addresses #617 and #1018

### CODE REVIEW

**Comment by duglin** [comment]
To address @n3wscott's questions in #617, do we need to say something about how the sender of the callback would need to use headers if they wanted to modify some of the flags like rate-limit ? And while it can be done via a GET or POST, doing it just from a browser isn't quite really that easy.

**Comment by clemensv** [comment]
GET accepts the proposed values by the caller. Makes sense to clarify.

**Comment by duglin** [comment]
@n3wscott do these changes address your concerns?

**Comment by duglin** [comment]
@krancour does this address your concerns from #1018 ?

**Review by n3wscott — APPROVED** [review]

**Comment by duglin** [comment]
Approved on the 8/25 call

**Pull request merged**
