### PR TITLE
Administrivia nits

### PR DESCRIPTION
**Pull request by duglin**
- fix mailing list info
- add pointer to the shanghai presentations
- add refs to our SDK work
- remove old f2f comment

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
If I could get a couple of eyes on this one, we can merge it w/o waiting for the weekly call.

**Comment by sslavic** [comment]
LGTM

**Comment by JemDay** [comment]
LGTM

**Comment by duglin** [comment]
thanks guys! merging

**Pull request merged**
