### PR TITLE
use camelCase in our property names

### PR DESCRIPTION
**Pull request by duglin**
Closes: #141

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by SeanFeldman** [comment]
LGTM

**Comment by dklyle** [comment]
LGTM

**Comment by ac360** [comment]
LGTM

**Comment by markpeek** [comment]
LGTM

**Comment by inlined** [comment]
LGTM. I think you meant "words that are acronyms" not "words that are abbreviations".

Some style guides set a maximum acronym length for capitalization.

**Comment by duglin** [comment]
@inlined fixed - thanks

**Comment by duglin** [comment]
Approved during 4/12 call.

**Pull request merged**
