### PR TITLE
Update SDK support status for RocketMQ binding

### LINKED ISSUE #1207: Update SDK support status for RocketMQ binding
Since https://github.com/cloudevents/sdk-java/pull/554 has been merged, we need to update the status of RocketMQ in SDK.md

### PR DESCRIPTION
**Pull request by aaron-ai**
Fixes #1207 

## Proposed Changes

- Update SDK support status for RocketMQ binding

**Release Note**

N/A

### CODE REVIEW

**Comment by duglin** [comment]
Thanks!
LGTM

**Comment by jskeet** [comment]
Is the RocketMQ binding documented in this repo? (I can't see it.) I'd personally prefer to keep the SDK table to "standards we've defined in this repo". Happy to be persuaded otherwise though - or just directed at the RocketMQ page in this repo if I've missed it :)

**Comment by pierDipi** [comment]
What's the reason for not mentioning it here?

CloudEvents will win when users will have the broader ecosystem support and easy access for users to underlying technologies and integrations for such technologies (including documentation and visibility).

If someone is evaluating CloudEvents and is already using or has easy access to whatever technology we integrate with, giving visibility can only help CloudEvents and the broader ecosystem.

**Comment by duglin** [comment]
We chatted about this on today's call and @jskeet will add a comment about some of the options we discussed.

**Comment by jskeet** [comment]
We came up with two options which would be preferable to me personally:

Option 1: Create a new section within the existing table, to clearly separate out the "CE-working-group-owned" specs from the proprietary specs.

Option 2 (preferred by me): Just add links to the [proprietary bindings/formats](https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md) page - in this case, a single sub-bullet saying "This is implemented by the Java SDK" with a link to it would be fine, IMO.

Motivation: I think it's reasonable to encourage SDK owners to implement all of the bindings/formats in the core repo, as far as they have time. But I don't want owners to feel under any pressure to implement proprietary specs.

**Comment by duglin** [comment]
I'm leaning towards option 1 because I fear that users of the SDK will rarely look at the [proprietary bindings/formats](https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md) page and not get the benefit of the status we're adding, or have the benefit of (by accident) noticing that one of the SDK supports one of those "other" bindings.

**Comment by jskeet** [comment]
> I'm leaning towards option 1 because I fear that users of the SDK will rarely look at the [proprietary bindings/formats](https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md) page and not get the benefit of the status we're adding, or have the benefit of (by accident) noticing that one of the SDK supports one of those "other" bindings.

How about option 2 + a node on the SDK page saying "Some SDKs support proprietary bindings as well. For more details see (link to page)"?

**Comment by pierDipi** [comment]
fwiw, I'm +1 on option 1.

> Motivation: I think it's reasonable to encourage SDK owners to implement all of the bindings/formats in the core repo, as far as they have time. But I don't want owners to feel under any pressure to implement proprietary specs.

I see and I agree, this should not be forced, however, I believe we can clarify this so that there is not confusion

**Comment by duglin** [comment]
@aaron-ai we chatted about this on today's call. Would be willing to change the PR to do option 1? Create a new section for "Proprietary Bindings" after the "Bindings / Content Modes" section?

**Comment by aaron-ai** [comment]
> @aaron-ai we chatted about this on today's call. Would be willing to change the PR to do option 1? Create a new section for "Proprietary Bindings" after the "Bindings / Content Modes" section?

Thanks! I will update this pull request later.

**Comment by aaron-ai** [comment]
@duglin PTAL

**Comment by duglin** [comment]
Looks like what we discussed on today's call - thanks a ton!
ping @jskeet

**Review by jskeet — APPROVED** [review]
Works for me, thanks!

**Pull request merged**
