### PR TITLE
NATS transport binding

### PR DESCRIPTION
**Pull request by ColinSullivan1**
I'd like to propose a [NATS](https://nats.io) transport binding for CloudEvents, similar to the [HTTP](https://github.com/cloudevents/spec/pull/148) binding and proposed [MQTT](https://github.com/cloudevents/spec/pull/158) and [AMQP](https://github.com/cloudevents/spec/pull/157) bindings.  This PR borrows heavily from the MQTT proposal.

Signed-off-by: Colin Sullivan <colin@synadia.com>

### CODE REVIEW

**Comment by duglin** [comment]
Nice!!

**Comment by duglin** [comment]
@ColinSullivan1 can you sign your commit?

**Comment by ColinSullivan1** [comment]
@duglin , Will do!

**Comment by ColinSullivan1** [comment]
I'll resubmit the PR, something happened w/ my git history.  Stay tuned.  :)

**Comment by ColinSullivan1** [comment]
Resubmitted as https://github.com/cloudevents/spec/pull/215

**Pull request closed without merging**
