### PR TITLE
fixed link typo

### PR DESCRIPTION
**Pull request by delabassee**
Signed-off-by: David Delabassée <david.delabassee@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
@delabassee thanks! can you please sign your commit?

**Comment by duglin** [comment]
it may be missing the "<>" around your email address. Or use the "-s" on the "git commit" command.

**Comment by delabassee** [comment]
Hmmm, I had "<>" around my email in my initial commit?! I hope it now works.

**Comment by duglin** [comment]
@delabassee all commits will need to be signed. You might find it easier to squash them down to one and then make sure that one has the signature in the right format.

**Comment by duglin** [comment]
Closing since #174 was opened to get around the dco issue

**Pull request closed without merging**
