### PR TITLE
Update spec.md

### PR DESCRIPTION
**Pull request by lfourie**
Signed-off-by: lfourie <louis.fourie@huawei.com>

### CODE REVIEW

**Comment by duglin** [comment]
@lfourie what is your git client's "user.name" value? I think it needs to match what's listed in the DCO of the commit.

**Comment by lfourie** [comment]
Signed-off-by: lfourie louis.fourie@huawei.com

**Comment by duglin** [comment]
So, in this case I think it needs to be "Louis Fourie"

**Comment by duglin** [comment]
@lfourie you can fix an existing commit by using: git commit --amend -s
that will allow you to edit the commit message and the -s will add your signature if not already there.
No need to open new PRs. If you have more than one commit, you may find it easier to just squash them down to one.

**Pull request closed without merging**
