### PR TITLE
Update Documents table formatting (use centering + remove extra spaces)

### PR DESCRIPTION
**Pull request by tsurdilo**
Just fixes formatting of the Documents table in readme

### CODE REVIEW

**Comment by duglin** [comment]
So, I'm ok with this however, I'm not looking forward to dueling md formating wars :-)

@n3wscott runs our md files thru prettier.io occasionally and I believe that's what caused the extras spaces to be there in the first place.  Scott - any thoughts/comments?

**Comment by tsurdilo** [comment]
It's just formatting changes, reason being I tried using this table for serverless workflow spec readme and got a headache trying to figure out where one row ends and new one begins ..so decided to make it clear :)

**Comment by n3wscott** [comment]
Na, don't do this change. Use pretter.io. There is a command line tool to fix the table spacing. No spacing is harder to read as markdown as a human, just look at the .md file as text.

**Comment by n3wscott** [comment]
> trying to figure out where one row ends and new one begins

don't look at the file on github raw, look at the file in a non-wrapping editor.

**Comment by duglin** [comment]
@n3wscott do you know if there's an option on prettier.io to squash those spaces?

**Comment by n3wscott** [comment]
the whole point of markdown is that it is readable both as a text file and as rendered pages.

a table that has no spaces (assuming your editor does not auto-wrap) is unreadable as text.

**Comment by tsurdilo** [comment]
@n3wscott again I am completely fine with dropping this pr, but I use VSCode editor and here is the differences:

** current **
Screen Shot 2020-03-18 at 10 20 56 PM

** in this pr **
Screen Shot 2020-03-18 at 10 23 15 PM

**Comment by tsurdilo** [comment]
Closing this pr as change not needed. Thanks for reviews!

**Comment by n3wscott** [comment]
Yeah like I said, markdown tables without wrapping in text mode is how they should be viewed. But still I find the version with spaces more readable. It becomes very clear for tables that have several columns and sparse filling.

**Pull request closed without merging**
