### PR TITLE
add video from Clemens

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by sslavic** [comment]
LGTM

**Comment by SeanFeldman** [comment]
Question: a link could break. Would it make sense to capture the binary (PPTX) within this repository?

**Comment by duglin** [comment]
@SeanFeldman good point, I forgot that he made the ppt available. I'll grab that and add it to the PR.

**Comment by duglin** [comment]
Done. The deletes are just old files that I renamed to not have spaces in the names.

**Comment by SeanFeldman** [comment]
👍

**Comment by ultrasaurus** [comment]
This PR seems to be deleting `share/2018-02-22 CloudEvents.pdf` -- am I reading that correctly?

**Comment by duglin** [comment]
@ultrasaurus yes - weird, for some reason I thought I added a comment about how those were old files that I forgot to erase when I renamed things to not have spaces in the names. Sorry, the comment must have just been in my head :-)

**Comment by ultrasaurus** [comment]
@duglin I think those were from a presentation from @yaronha before we had an index.  Deleting old content should be in a different PR (and not sure these should be deleted -- would need to go back thru notes to be sure)

**Comment by duglin** [comment]
@ultrasaurus I didn't delete content, I just renamed it and forgot to delete the old named version.

**Comment by duglin** [comment]
Approved on 3/29 call

**Pull request merged**
