### PR TITLE
Update demos.md: adding Microcks talk and live demo recording and blo…

### PR DESCRIPTION
**Pull request by yada**
Update demos.md: adding Microcks talk and live demo recording and blog post

Fixes #

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by duglin** [comment]
LGTM thanks

**Review by jskeet — APPROVED** [review]
This is fine, but we should probably decide on chronological or reverse-chronological order, and be consistent with it.

**Comment by yada** [comment]
@jskeet, thanks for the feedback. I fully agree with your comment: I have had some doubts about where to have our entry...
I used the recording date, the latest at the top (seems to be ours: 2021). But I'm happy to change/update it if you want; let me know.

**Comment by duglin** [comment]
Approved on the 3/28 call. @yada once you reorder things so the newest stuff is first, I'll merge it.

**Comment by yada** [comment]
Thanks, @duglin; I am happy to make any changes, but if the newest is the first, then I guess it is already the case with my PR, no?
Capture d’écran 2024-03-28 à 20 27 27

Sorry if I missed something. Please let me know or re-order accordingly; fine with me.

**Comment by duglin** [comment]
True, yours is newest/first, but I think the order of the others should be:
- [Gaining business visibility into processes implement by Cloud Events](https://blog.bernd-ruecker.com/gaining-visibility-into-processes-spanning-multiple-microservices-a1fc751c4c13) - Jun 23, 2020
- [Orchestrating Cloud Events](https://salaboy.com/2020/05/18/orchestrating-cloud-events-with-zeebe/) - May 18, 2020
- CNCF/Kube-Con NA December 2018
- CNCF/Kube-Con EU May 2018

Maybe add the dates to 2 & 3 too :-)

**Comment by yada** [comment]
@duglin ✅ I also have unified the date format and reordered as requested: +1
Let me know if it is ok for you?

**Comment by duglin** [comment]
perfect - thanks for the extra fixes!
Merging.

**Pull request merged**
