### PR TITLE
v1.0 release and vote

### PR DESCRIPTION
**Pull request by duglin**
Please add your LGTM to this PR if you approve of v1.0

Eligible voters are:  Enterprise Holdings, Google, IBM, Microsoft, NATS/Synadia, PayPal, Platform9, Red Hat, RX-M, SAP, VMWare, Vlad Ionescu, Erik Erikson, John Mitchell

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by ac360** [comment]
Exciting :)

**Comment by clemensv** [comment]
LGTM. Microsoft votes for v1.0

**Comment by alexouzounis** [comment]
exciting stuff :)

**Comment by Vlaaaaaaad** [comment]
LGTM. There are no outstanding issues or concerns so let's ship this!

**Comment by ColinSullivan1** [comment]
LGTM.

**Comment by duglin** [comment]
IBM votes +1 for 1.0

**Comment by erikerikson** [comment]
LGTM

**Comment by n3wscott** [comment]
Google votes +1 for 1.0

**Comment by deissnerk** [comment]
LGTM 
+1 for 1.0 from SAP

**Comment by markpeek** [comment]
VMware votes +1 for 1.0

**Comment by johnm** [comment]
LGTM.  +1 for 1.0

**Comment by markito** [comment]
LGTM! Red Hat votes +1 for v1.0 - Congratulations everyone!

**Comment by JemDay** [comment]
PayPal Votes +1 for 1.0

**Comment by duglin** [comment]
Yes: Google, IBM, Microsoft, NATS, PayPal, RedHat, SAP, VMware, Vlad Ionescu, Erik Erikson, John Mitchell
Passed: 11 Yes, 0 No

**Pull request merged**
