### PR TITLE
Add cloudevents-python & CloudEvents.live to open-source

### PR DESCRIPTION
**Pull request by williamhogman**
This adds the cloudevents-python library and the CloudEvents.live debugger.

Signed-off-by: William Rudenmalm <me@whn.se>

### CODE REVIEW

**Comment by almghayreh** [comment]
Nice..

**Comment by duglin** [comment]
rebase needed

**Comment by williamhogman** [comment]
Done.

**Comment by duglin** [comment]
thanks
LGTM

**Pull request merged**
